# Generated by Django 4.2.3 on 2023-07-31 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_task', '0004_alter_task_priority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-priority']},
        ),
    ]
